// Code generated by cmd/gen. DO NOT EDIT.

package model

type CategoryKind string

const (
	CategoryKindBasicScience CategoryKind = "basic-science"
	CategoryKindClinical     CategoryKind = "clinical"
	CategoryKindOther        CategoryKind = "other"
)

type Category struct {
	ID     string       `json:"id,omitempty"`
	Kind   CategoryKind `json:"kind,omitempty"`
	Name   string       `json:"name,omitempty"`
	Parent *string      `json:"parent,omitempty"`
}

type Product struct{}

type Article struct{}
